#!/usr/bin/env bash

if [ ! -d $HOME/Documents/shell-config ]; then
  mkdir -p $HOME/Documents/shell-config
fi

temp=$(mktemp -d)
cp -r $HOME/.config/iterm2 $temp/
cp -r $HOME/.config/karabiner $temp/
cp -r $HOME/.config/git $temp/
cp -r $temp/* $HOME/Documents/shell-config/
rm -rf $temp
