#!/bin/bash

mkdir -p stats/$(date -I)
mv stats/code* stats/$(date -I)
sloc --exclude "node_modules|bundle|web_modules" . > stats/codestats.txt
cloc ./ --exclude-dir=node_modules,web_modules --exclude-ext=json --use-sloccount --csv --by-file --report-file stats/codecount.csv


