#!/usr/bin/bash

file=$(mktemp)

ipsh=$(hostname -I)
ips=$(curl -s icanhazip.com)
ips4=$(curl -s ipv4.icanhazip.com)
for ip in "$ipsh $ips4 $ips6"
do
  echo $ip >> $file
  #hs=$(dig -x $ip +short)
  #if [[ ! -z "$hs" ]]
  #then
  #  echo "$hs"
  #fi
done

uip=$(sort $file | uniq)
rm $file
file=$(mktemp)
for ip in $uip
do
  hs=$(dig -x $ip +short)
  if [[ ! -z "$hs" ]]
  then
    echo "$hs" >> $file
  fi
done

hosts=$(sort $file | uniq)
echo $hosts

rm $file
